Vec 95
aerospike/aerospike-vector-search-examples pull request #27
Opened 2024-05-07 12:07 UTC by davi17g

2024-05-07 17:43 UTC, hev requested changes
@davi17g we have a newer client version than this one. This is probably a bigger change to make as there are some name changes involved in the API. We should track this under VEC-134.

2024-05-07 17:43 UTC, hev commented on basic-search/requirements.txt
> +aerospike-proximus==0.3.2.dev1
This should use aerospike-vector-search client 0.5.1 now - which may break some other functionality and require input from @jdogmcsteezy.

2024-05-07 20:32 UTC, arrowplum reviewed
In general we should make sure the READMEs have the new configuration

2024-05-07 20:32 UTC, arrowplum commented on prism-image-search/prism/config.py
> +    PROXIMUS_IS_LOADBALANCER = os.environ.get("PROXIMUS_IS_LOADBALANCER") or False
I think we are missing these values in the readme

2024-05-07 20:59 UTC, hev commented on prism-image-search/prism/config.py
> +    PROXIMUS_IS_LOADBALANCER = os.environ.get("PROXIMUS_IS_LOADBALANCER") or False
I came across a few things in the README I think we should put into another PR.

2024-05-07 20:59 UTC, hev commented on basic-search/requirements.txt
> +aerospike-proximus==0.3.2.dev1
Agreed. Resolving.

2024-05-07 21:00 UTC, hev approved these changes
Tested using docker-compose and a sandbox. All works.

2024-05-08 01:29 UTC, arrowplum approved these changes
Tested built against the sandbox and the published https://hub.docker.com/repository/docker/aerospike/quote-search-example/

Also experimental helm chart works fine with a few small tweaks. :+1: 

@davi17g I think you can go ahead and merge it.

2024-05-08 12:24 UTC, merged