feat: vec-92 use pre-embedded quote data set
aerospike/aerospike-vector-search-examples pull request #52
Opened 2024-08-09 22:00 UTC by dwelch-spike

2024-08-09 22:37 UTC, jdogmcsteezy commented on quote-semantic-search/quote-search/indexer.py
> +    embedding = ast.literal_eval(embedding)
need a comment to say what this is doing

2024-08-09 22:37 UTC, jdogmcsteezy commented on quote-semantic-search/quote-search/indexer.py
> +    embedding = ast.literal_eval(embedding)
We need this to be really easy code to understand

2024-08-09 22:43 UTC, jdogmcsteezy requested changes
small changes

2024-08-09 22:43 UTC, jdogmcsteezy commented on quote-semantic-search/scripts/pre-embed.py
> +# The image or text encoding model.
```suggestion
# The text encoding model.
```

2024-08-09 22:43 UTC, jdogmcsteezy commented on quote-semantic-search/scripts/requirements.txt
This file is not needed. It has dependencies also quote-search/requirements.txt and they should remain in sync.

2024-08-09 22:43 UTC, jdogmcsteezy commented on quote-semantic-search/quote-search/indexer.py
> +    quote, author, catagory, embedding = quote
add comment to explain that quote is pre-embedded. Good to mention it incase they did not read the README

2024-08-09 22:43 UTC, jdogmcsteezy commented on quote-semantic-search/scripts/pre-embed.py
> +MODEL_DIM = 384
Anyway to pull this info from indexer.py? These should also stay in sync

2024-08-12 21:49 UTC, dwelch-spike commented on quote-semantic-search/scripts/requirements.txt
Deleted it.

2024-08-12 21:50 UTC, dwelch-spike commented on quote-semantic-search/quote-search/indexer.py
> +    quote, author, catagory, embedding = quote
Left a detailed comment.

2024-08-13 16:19 UTC, jdogmcsteezy approved these changes
bigger comment than I was expecting :) feel free to shorten it if you wish haha

2024-08-13 16:36 UTC, merged